export const SET_RECIPES = 'SET_RECIPES';
export const SET_RECIPE_DETAIL = 'SET_RECIPE_DETAIL';
export const SET_CLEAR_RECIPE_RESPONSE = 'SET_CLEAR_RECIPE_RESPONSE';
export const SET_CREATE_RECIPE_RESPONSE = 'SET_CREATE_RECIPE_RESPONSE';
